#!/bin/bash

if tmux has-session -t music 2>/dev/null; then
  echo 'Attaching to music'
else
  tmux new-session -d -s music
  tmux rename-window rmpc
  tmux send-keys rmpc C-m
fi

tmux attach-session -t music
